fix(cicd): use npm oidc in npm publish

diff --git a/.github/workflows/.publish-npm.yml b/.github/workflows/.publish-npm.yml
--- a/.github/workflows/.publish-npm.yml
+++ b/.github/workflows/.publish-npm.yml
@@ -2,10 +2,9 @@ name: .publish-npm
 
 on:
   workflow_call:
-    secrets:
-      npm-auth-token:
-        required: true
-        description: required credentials to authenticate with the aws account under which to publish
+
+permissions:
+  id-token: write # required for oidc
 
 jobs:
   install:
@@ -21,7 +20,7 @@ jobs:
       - name: set node-version
         uses: actions/setup-node@v4
         with:
-          registry-url: "https://registry.npmjs.org/"
+          registry-url: "https://registry.npmjs.org/" # required to publish
           node-version-file: ".nvmrc"
 
       - name: node-modules cache get
@@ -31,14 +30,21 @@ jobs:
           path: ./node_modules
           key: ${{ needs.install.outputs.node-modules-cache-key }}
 
-      - name: node-modules cache miss install
-        if: steps.cache.outputs.cache-hit != 'true'
-        run: npm ci --ignore-scripts --prefer-offline --no-audit
+      - name: verify oidc
+        run: |
+          OIDC_TOKEN=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=npm:registry.npmjs.org" | jq -r '.value')
+          PACKAGE_NAME_PLAIN=$(jq -r '.name' package.json)
+          PACKAGE_NAME_ENCODED=$(printf '%s' "$PACKAGE_NAME_PLAIN" | jq -sRr @uri)
+          HTTP_CODE=$(curl -sS -o /dev/null -w '%{http_code}' -X POST -H "Authorization: Bearer $OIDC_TOKEN" "https://registry.npmjs.org/-/npm/v1/oidc/token/exchange/package/$PACKAGE_NAME_ENCODED")
+          if [ "$HTTP_CODE" = "200" ]; then
+            echo "oidc: configured for $PACKAGE_NAME_PLAIN"
+          else
+            echo "::error::oidc: not configured for $PACKAGE_NAME_PLAIN (http $HTTP_CODE). add oidc by-hand at https://www.npmjs.com/package/$PACKAGE_NAME_ENCODED/access"
+            exit 1
+          fi
 
       - name: build
         run: npm run build
 
       - name: publish
-        run: npm publish --access public
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.npm-auth-token }}
+        run: npm publish --access public --provenance
